# Generated by Django 2.1 on 2018-09-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectureroom',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('nfcid', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'lectureroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('admin', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendancerecord',
            fields=[
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deuluwa.User')),
                ('attendanced', models.BooleanField()),
                ('attendancetime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendancerecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courseinformation',
            fields=[
                ('index', models.ForeignKey(db_column='index', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deuluwa.Course')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('starttime', models.CharField(max_length=4)),
                ('coursetime', models.IntegerField()),
                ('classday', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'courseinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinformation',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deuluwa.User')),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userinformation',
                'managed': False,
            },
        ),
    ]
