# Generated by Django 2.1.1 on 2018-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuluwa', '0002_coursestudent_loginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
    ]
